services:
  web:
    build: .
    command: bash -c "python manage.py migrate &&  python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    depends_on:
      - web
    volumes:
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
