# Generated by Django 5.2.7 on 2025-10-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("played_at", models.DateTimeField(auto_now_add=True)),
                ("oka_value", models.IntegerField(default=20000)),
                ("start_score", models.IntegerField(default=25000)),
                ("target_score", models.IntegerField(default=30000)),
                ("uma_top", models.IntegerField(default=20)),
                ("uma_second", models.IntegerField(default=10)),
                ("uma_third", models.IntegerField(default=-10)),
                ("uma_last", models.IntegerField(default=-20)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_raw", models.IntegerField()),
                ("score_adjusted", models.FloatField(null=True)),
                ("rank", models.PositiveSmallIntegerField(null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.player"
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "player")},
            },
        ),
    ]
