# Generated by Django 5.2.7 on 2025-10-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_avatar_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='allow_randomize',
            field=models.BooleanField(default=False),
        ),
    ]
