# Generated by Django 5.2.7 on 2025-10-25 17:26

from django.db import migrations, models


def repopulate_uma_oka(apps, schema_editor):
    Game = apps.get_model('games', 'Game')
    GameResult = apps.get_model('games', 'GameResult')

    Game.objects.all().update(target_score=25000, uma_top=15, uma_second=5, uma_third=-5, uma_last=-15)

    for game in Game.objects.all():
        results = list(GameResult.objects.filter(game=game).order_by('-score_raw', 'id'))
        if len(results) != 4:
            continue

        uma_values = [game.uma_top, game.uma_second, game.uma_third, game.uma_last]
        for rank, (result, uma) in enumerate(zip(results, uma_values), start=1):
            diff_from_target = (result.score_raw - game.target_score) / 1000
            if rank == 1:
                diff_from_target += game.oka_value / 1000
            result.rank = rank
            result.score_adjusted = diff_from_target + uma
            result.save(update_fields=['rank', 'score_adjusted'])


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_avatar_allow_randomize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='target_score',
            field=models.IntegerField(default=25000),
        ),
        migrations.AlterField(
            model_name='game',
            name='uma_last',
            field=models.IntegerField(default=-15),
        ),
        migrations.AlterField(
            model_name='game',
            name='uma_second',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='uma_third',
            field=models.IntegerField(default=-5),
        ),
        migrations.AlterField(
            model_name='game',
            name='uma_top',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='player',
            name='clubs',
            field=models.ManyToManyField(related_name='players', to='games.club'),
        ),
        migrations.RunPython(
            code=repopulate_uma_oka,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
    ]
