# Generated by Django 5.2.7 on 2025-10-25 17:26

from django.db import migrations, models


def repopulate_uma_oka(apps, schema_editor):
    from games.models import Game
    Game.objects.all().update(target_score=25000, uma_top=15, uma_second=5, uma_third=-5, uma_last=-15)
    for game in Game.objects.all():
        game.calculate_final_scores()


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_avatar_allow_randomize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='target_score',
            field=models.IntegerField(default=25000),
        ),
        migrations.AlterField(
            model_name='game',
            name='uma_last',
            field=models.IntegerField(default=-15),
        ),
        migrations.AlterField(
            model_name='game',
            name='uma_second',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='uma_third',
            field=models.IntegerField(default=-5),
        ),
        migrations.AlterField(
            model_name='game',
            name='uma_top',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='player',
            name='clubs',
            field=models.ManyToManyField(related_name='players', to='games.club'),
        ),
        migrations.RunPython(
            code=repopulate_uma_oka,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
    ]
