# Generated by Django 5.2.9 on 2026-01-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gamehighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_unranked',
            field=models.BooleanField(default=False, help_text='Unranked game will not affect stats', verbose_name='Unranked game'),
        ),
    ]
