name: Build and Deploy to Droplet

on:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  APP_NAME: riichi-tracker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REMOTE_DIR: ${{ vars.REMOTE_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create deployment archive
        run: |
          tar \
            --exclude-vcs \
            --exclude='.github' \
            --exclude='.idea' \
            --exclude='.env' \
            --exclude='db/*.sqlite3' \
            -czf app.tar.gz .

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add droplet to known_hosts
        env:
          SSH_HOST: ${{ secrets.DROPLET_HOST }}
          SSH_PORT: ${{ secrets.DROPLET_PORT != '' && secrets.DROPLET_PORT || '22' }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Create remote app directory
        env:
          SSH_HOST: ${{ secrets.DROPLET_HOST }}
          SSH_USER: ${{ secrets.DROPLET_USER }}
          SSH_PORT: ${{ secrets.DROPLET_PORT != '' && secrets.DROPLET_PORT || '22' }}
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" \
            'set -euo pipefail; REMOTE_DIR='"$REMOTE_DIR"'; mkdir -p "$REMOTE_DIR/db"'

      - name: Upload .env to droplet
        env:
          SSH_HOST: ${{ secrets.DROPLET_HOST }}
          SSH_USER: ${{ secrets.DROPLET_USER }}
          SSH_PORT: ${{ secrets.DROPLET_PORT != '' && secrets.DROPLET_PORT || '22' }}
          VARS_ENV: ${{ vars.ENV }}
        run: |
          set -euo pipefail
          if [ -z "${VARS_ENV}" ]; then
            echo "vars.ENV is empty or undefined" >&2
            exit 1
          fi
          tmpfile=$(mktemp)
          # Preserve newlines exactly
          printf '%s\n' "$VARS_ENV" > "$tmpfile"
          scp -P "$SSH_PORT" "$tmpfile" "$SSH_USER@$SSH_HOST:$REMOTE_DIR/.env"
          rm -f "$tmpfile"

      - name: Upload app to droplet
        env:
          SSH_HOST: ${{ secrets.DROPLET_HOST }}
          SSH_USER: ${{ secrets.DROPLET_USER }}
          SSH_PORT: ${{ secrets.DROPLET_PORT != '' && secrets.DROPLET_PORT || '22' }}
        run: |
          scp -P "$SSH_PORT" app.tar.gz "$SSH_USER@$SSH_HOST:$REMOTE_DIR/app.tar.gz"

      - name: Unpack on droplet
        env:
          SSH_HOST: ${{ secrets.DROPLET_HOST }}
          SSH_USER: ${{ secrets.DROPLET_USER }}
          SSH_PORT: ${{ secrets.DROPLET_PORT != '' && secrets.DROPLET_PORT || '22' }}
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" \
            'set -euo pipefail; \
             REMOTE_DIR='"$REMOTE_DIR"'; \
             mkdir -p "$REMOTE_DIR"; \
             tar -xzf "$REMOTE_DIR/app.tar.gz" -C "$REMOTE_DIR"; \
             rm -f "$REMOTE_DIR/app.tar.gz"'
      
      - name: Ensure network and deploy (Compose)
        env:
          SSH_HOST: ${{ secrets.DROPLET_HOST }}
          SSH_USER: ${{ secrets.DROPLET_USER }}
          SSH_PORT: ${{ secrets.DROPLET_PORT != '' && secrets.DROPLET_PORT || '22' }}
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" \
            'set -euo pipefail; \
             REMOTE_DIR='"$REMOTE_DIR"'; \
             cd "$REMOTE_DIR"; \
             docker network create gateway >/dev/null 2>&1 || true; \
             docker compose -f docker-compose.prod.yml --project-name riichi-tracker up -d --build'
